/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as AuthenticatedShareRouteImport } from './routes/_authenticated/share'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSaveRouteImport } from './routes/_authenticated/save'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDevNotesRouteImport } from './routes/_authenticated/dev-notes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as ApiPublicUrlMetadataRouteImport } from './routes/api/public/url-metadata'
import { Route as ApiMeSaveTokenRouteImport } from './routes/api/me.save-token'
import { Route as AuthenticatedItemIdRouteImport } from './routes/_authenticated/item.$id'
import { Route as AuthenticatedCollectionsIdRouteImport } from './routes/_authenticated/collections.$id'
import { Route as AuthenticatedCategoryTypeRouteImport } from './routes/_authenticated/category.$type'
import { Route as ApiPublicShareSaveRouteImport } from './routes/api/public/share.save'
import { Route as ApiPublicItemsRecategorizeRouteImport } from './routes/api/public/items.recategorize'
import { Route as ApiPublicExtensionSaveRouteImport } from './routes/api/public/extension.save'
import { Route as ApiPublicExtensionCollectionsRouteImport } from './routes/api/public/extension.collections'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShareRoute = AuthenticatedShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSaveRoute = AuthenticatedSaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevNotesRoute = AuthenticatedDevNotesRouteImport.update({
  id: '/dev-notes',
  path: '/dev-notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicUrlMetadataRoute = ApiPublicUrlMetadataRouteImport.update({
  id: '/api/public/url-metadata',
  path: '/api/public/url-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeSaveTokenRoute = ApiMeSaveTokenRouteImport.update({
  id: '/api/me/save-token',
  path: '/api/me/save-token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedItemIdRoute = AuthenticatedItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsIdRoute =
  AuthenticatedCollectionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)
const AuthenticatedCategoryTypeRoute =
  AuthenticatedCategoryTypeRouteImport.update({
    id: '/category/$type',
    path: '/category/$type',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicShareSaveRoute = ApiPublicShareSaveRouteImport.update({
  id: '/api/public/share/save',
  path: '/api/public/share/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicItemsRecategorizeRoute =
  ApiPublicItemsRecategorizeRouteImport.update({
    id: '/api/public/items/recategorize',
    path: '/api/public/items/recategorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionSaveRoute = ApiPublicExtensionSaveRouteImport.update({
  id: '/api/public/extension/save',
  path: '/api/public/extension/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionCollectionsRoute =
  ApiPublicExtensionCollectionsRouteImport.update({
    id: '/api/public/extension/collections',
    path: '/api/public/extension/collections',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/ask': typeof AuthenticatedAskRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dev-notes': typeof AuthenticatedDevNotesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/save': typeof AuthenticatedSaveRoute
  '/search': typeof AuthenticatedSearchRoute
  '/share': typeof AuthenticatedShareRoute
  '/share/$slug': typeof ShareSlugRoute
  '/category/$type': typeof AuthenticatedCategoryTypeRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/item/$id': typeof AuthenticatedItemIdRoute
  '/api/me/save-token': typeof ApiMeSaveTokenRoute
  '/api/public/url-metadata': typeof ApiPublicUrlMetadataRoute
  '/api/public/extension/collections': typeof ApiPublicExtensionCollectionsRoute
  '/api/public/extension/save': typeof ApiPublicExtensionSaveRoute
  '/api/public/items/recategorize': typeof ApiPublicItemsRecategorizeRoute
  '/api/public/share/save': typeof ApiPublicShareSaveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/ask': typeof AuthenticatedAskRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dev-notes': typeof AuthenticatedDevNotesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/save': typeof AuthenticatedSaveRoute
  '/search': typeof AuthenticatedSearchRoute
  '/share': typeof AuthenticatedShareRoute
  '/share/$slug': typeof ShareSlugRoute
  '/category/$type': typeof AuthenticatedCategoryTypeRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/item/$id': typeof AuthenticatedItemIdRoute
  '/api/me/save-token': typeof ApiMeSaveTokenRoute
  '/api/public/url-metadata': typeof ApiPublicUrlMetadataRoute
  '/api/public/extension/collections': typeof ApiPublicExtensionCollectionsRoute
  '/api/public/extension/save': typeof ApiPublicExtensionSaveRoute
  '/api/public/items/recategorize': typeof ApiPublicItemsRecategorizeRoute
  '/api/public/share/save': typeof ApiPublicShareSaveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dev-notes': typeof AuthenticatedDevNotesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/save': typeof AuthenticatedSaveRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/share': typeof AuthenticatedShareRoute
  '/share/$slug': typeof ShareSlugRoute
  '/_authenticated/category/$type': typeof AuthenticatedCategoryTypeRoute
  '/_authenticated/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/_authenticated/item/$id': typeof AuthenticatedItemIdRoute
  '/api/me/save-token': typeof ApiMeSaveTokenRoute
  '/api/public/url-metadata': typeof ApiPublicUrlMetadataRoute
  '/api/public/extension/collections': typeof ApiPublicExtensionCollectionsRoute
  '/api/public/extension/save': typeof ApiPublicExtensionSaveRoute
  '/api/public/items/recategorize': typeof ApiPublicItemsRecategorizeRoute
  '/api/public/share/save': typeof ApiPublicShareSaveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/ask'
    | '/collections'
    | '/dashboard'
    | '/dev-notes'
    | '/profile'
    | '/reminders'
    | '/save'
    | '/search'
    | '/share'
    | '/share/$slug'
    | '/category/$type'
    | '/collections/$id'
    | '/item/$id'
    | '/api/me/save-token'
    | '/api/public/url-metadata'
    | '/api/public/extension/collections'
    | '/api/public/extension/save'
    | '/api/public/items/recategorize'
    | '/api/public/share/save'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/ask'
    | '/collections'
    | '/dashboard'
    | '/dev-notes'
    | '/profile'
    | '/reminders'
    | '/save'
    | '/search'
    | '/share'
    | '/share/$slug'
    | '/category/$type'
    | '/collections/$id'
    | '/item/$id'
    | '/api/me/save-token'
    | '/api/public/url-metadata'
    | '/api/public/extension/collections'
    | '/api/public/extension/save'
    | '/api/public/items/recategorize'
    | '/api/public/share/save'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/_authenticated/ask'
    | '/_authenticated/collections'
    | '/_authenticated/dashboard'
    | '/_authenticated/dev-notes'
    | '/_authenticated/profile'
    | '/_authenticated/reminders'
    | '/_authenticated/save'
    | '/_authenticated/search'
    | '/_authenticated/share'
    | '/share/$slug'
    | '/_authenticated/category/$type'
    | '/_authenticated/collections/$id'
    | '/_authenticated/item/$id'
    | '/api/me/save-token'
    | '/api/public/url-metadata'
    | '/api/public/extension/collections'
    | '/api/public/extension/save'
    | '/api/public/items/recategorize'
    | '/api/public/share/save'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ApiMeSaveTokenRoute: typeof ApiMeSaveTokenRoute
  ApiPublicUrlMetadataRoute: typeof ApiPublicUrlMetadataRoute
  ApiPublicExtensionCollectionsRoute: typeof ApiPublicExtensionCollectionsRoute
  ApiPublicExtensionSaveRoute: typeof ApiPublicExtensionSaveRoute
  ApiPublicItemsRecategorizeRoute: typeof ApiPublicItemsRecategorizeRoute
  ApiPublicShareSaveRoute: typeof ApiPublicShareSaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/share': {
      id: '/_authenticated/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof AuthenticatedShareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/save': {
      id: '/_authenticated/save'
      path: '/save'
      fullPath: '/save'
      preLoaderRoute: typeof AuthenticatedSaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev-notes': {
      id: '/_authenticated/dev-notes'
      path: '/dev-notes'
      fullPath: '/dev-notes'
      preLoaderRoute: typeof AuthenticatedDevNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/url-metadata': {
      id: '/api/public/url-metadata'
      path: '/api/public/url-metadata'
      fullPath: '/api/public/url-metadata'
      preLoaderRoute: typeof ApiPublicUrlMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/save-token': {
      id: '/api/me/save-token'
      path: '/api/me/save-token'
      fullPath: '/api/me/save-token'
      preLoaderRoute: typeof ApiMeSaveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/item/$id': {
      id: '/_authenticated/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof AuthenticatedItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$id': {
      id: '/_authenticated/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AuthenticatedCollectionsIdRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
    '/_authenticated/category/$type': {
      id: '/_authenticated/category/$type'
      path: '/category/$type'
      fullPath: '/category/$type'
      preLoaderRoute: typeof AuthenticatedCategoryTypeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/share/save': {
      id: '/api/public/share/save'
      path: '/api/public/share/save'
      fullPath: '/api/public/share/save'
      preLoaderRoute: typeof ApiPublicShareSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/items/recategorize': {
      id: '/api/public/items/recategorize'
      path: '/api/public/items/recategorize'
      fullPath: '/api/public/items/recategorize'
      preLoaderRoute: typeof ApiPublicItemsRecategorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/save': {
      id: '/api/public/extension/save'
      path: '/api/public/extension/save'
      fullPath: '/api/public/extension/save'
      preLoaderRoute: typeof ApiPublicExtensionSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/collections': {
      id: '/api/public/extension/collections'
      path: '/api/public/extension/collections'
      fullPath: '/api/public/extension/collections'
      preLoaderRoute: typeof ApiPublicExtensionCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCollectionsRouteChildren {
  AuthenticatedCollectionsIdRoute: typeof AuthenticatedCollectionsIdRoute
}

const AuthenticatedCollectionsRouteChildren: AuthenticatedCollectionsRouteChildren =
  {
    AuthenticatedCollectionsIdRoute: AuthenticatedCollectionsIdRoute,
  }

const AuthenticatedCollectionsRouteWithChildren =
  AuthenticatedCollectionsRoute._addFileChildren(
    AuthenticatedCollectionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevNotesRoute: typeof AuthenticatedDevNotesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSaveRoute: typeof AuthenticatedSaveRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedShareRoute: typeof AuthenticatedShareRoute
  AuthenticatedCategoryTypeRoute: typeof AuthenticatedCategoryTypeRoute
  AuthenticatedItemIdRoute: typeof AuthenticatedItemIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevNotesRoute: AuthenticatedDevNotesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSaveRoute: AuthenticatedSaveRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedShareRoute: AuthenticatedShareRoute,
  AuthenticatedCategoryTypeRoute: AuthenticatedCategoryTypeRoute,
  AuthenticatedItemIdRoute: AuthenticatedItemIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
  ShareSlugRoute: ShareSlugRoute,
  ApiMeSaveTokenRoute: ApiMeSaveTokenRoute,
  ApiPublicUrlMetadataRoute: ApiPublicUrlMetadataRoute,
  ApiPublicExtensionCollectionsRoute: ApiPublicExtensionCollectionsRoute,
  ApiPublicExtensionSaveRoute: ApiPublicExtensionSaveRoute,
  ApiPublicItemsRecategorizeRoute: ApiPublicItemsRecategorizeRoute,
  ApiPublicShareSaveRoute: ApiPublicShareSaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
