/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSaveRouteImport } from './routes/_authenticated/save'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedCollectionsIdRouteImport } from './routes/_authenticated/collections.$id'
import { Route as ApiPublicShareSaveRouteImport } from './routes/api/public/share.save'
import { Route as ApiPublicExtensionSaveRouteImport } from './routes/api/public/extension.save'
import { Route as ApiPublicExtensionCollectionsRouteImport } from './routes/api/public/extension.collections'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSaveRoute = AuthenticatedSaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsIdRoute =
  AuthenticatedCollectionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)
const ApiPublicShareSaveRoute = ApiPublicShareSaveRouteImport.update({
  id: '/api/public/share/save',
  path: '/api/public/share/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionSaveRoute = ApiPublicExtensionSaveRouteImport.update({
  id: '/api/public/extension/save',
  path: '/api/public/extension/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionCollectionsRoute =
  ApiPublicExtensionCollectionsRouteImport.update({
    id: '/api/public/extension/collections',
    path: '/api/public/extension/collections',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ask': typeof AuthenticatedAskRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/save': typeof AuthenticatedSaveRoute
  '/search': typeof AuthenticatedSearchRoute
  '/share/$slug': typeof ShareSlugRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/api/public/extension/collections': typeof ApiPublicExtensionCollectionsRoute
  '/api/public/extension/save': typeof ApiPublicExtensionSaveRoute
  '/api/public/share/save': typeof ApiPublicShareSaveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ask': typeof AuthenticatedAskRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/save': typeof AuthenticatedSaveRoute
  '/search': typeof AuthenticatedSearchRoute
  '/share/$slug': typeof ShareSlugRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/api/public/extension/collections': typeof ApiPublicExtensionCollectionsRoute
  '/api/public/extension/save': typeof ApiPublicExtensionSaveRoute
  '/api/public/share/save': typeof ApiPublicShareSaveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/save': typeof AuthenticatedSaveRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/share/$slug': typeof ShareSlugRoute
  '/_authenticated/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/api/public/extension/collections': typeof ApiPublicExtensionCollectionsRoute
  '/api/public/extension/save': typeof ApiPublicExtensionSaveRoute
  '/api/public/share/save': typeof ApiPublicShareSaveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ask'
    | '/collections'
    | '/dashboard'
    | '/profile'
    | '/save'
    | '/search'
    | '/share/$slug'
    | '/collections/$id'
    | '/api/public/extension/collections'
    | '/api/public/extension/save'
    | '/api/public/share/save'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ask'
    | '/collections'
    | '/dashboard'
    | '/profile'
    | '/save'
    | '/search'
    | '/share/$slug'
    | '/collections/$id'
    | '/api/public/extension/collections'
    | '/api/public/extension/save'
    | '/api/public/share/save'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ask'
    | '/_authenticated/collections'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/save'
    | '/_authenticated/search'
    | '/share/$slug'
    | '/_authenticated/collections/$id'
    | '/api/public/extension/collections'
    | '/api/public/extension/save'
    | '/api/public/share/save'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ApiPublicExtensionCollectionsRoute: typeof ApiPublicExtensionCollectionsRoute
  ApiPublicExtensionSaveRoute: typeof ApiPublicExtensionSaveRoute
  ApiPublicShareSaveRoute: typeof ApiPublicShareSaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/save': {
      id: '/_authenticated/save'
      path: '/save'
      fullPath: '/save'
      preLoaderRoute: typeof AuthenticatedSaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$id': {
      id: '/_authenticated/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AuthenticatedCollectionsIdRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
    '/api/public/share/save': {
      id: '/api/public/share/save'
      path: '/api/public/share/save'
      fullPath: '/api/public/share/save'
      preLoaderRoute: typeof ApiPublicShareSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/save': {
      id: '/api/public/extension/save'
      path: '/api/public/extension/save'
      fullPath: '/api/public/extension/save'
      preLoaderRoute: typeof ApiPublicExtensionSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/collections': {
      id: '/api/public/extension/collections'
      path: '/api/public/extension/collections'
      fullPath: '/api/public/extension/collections'
      preLoaderRoute: typeof ApiPublicExtensionCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCollectionsRouteChildren {
  AuthenticatedCollectionsIdRoute: typeof AuthenticatedCollectionsIdRoute
}

const AuthenticatedCollectionsRouteChildren: AuthenticatedCollectionsRouteChildren =
  {
    AuthenticatedCollectionsIdRoute: AuthenticatedCollectionsIdRoute,
  }

const AuthenticatedCollectionsRouteWithChildren =
  AuthenticatedCollectionsRoute._addFileChildren(
    AuthenticatedCollectionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSaveRoute: typeof AuthenticatedSaveRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSaveRoute: AuthenticatedSaveRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ShareSlugRoute: ShareSlugRoute,
  ApiPublicExtensionCollectionsRoute: ApiPublicExtensionCollectionsRoute,
  ApiPublicExtensionSaveRoute: ApiPublicExtensionSaveRoute,
  ApiPublicShareSaveRoute: ApiPublicShareSaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
